### PR TITLE
Create decoding_string.cpp

### PR DESCRIPTION
**Pull request by Aarti002**
-leetcode
-top 100 liked questions
-decoding string

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
create a PR that contains at least 5 Questions

**Review by Siddhant-K-code — APPROVED** [review]
Add 4 more questions atleast

**Comment by Aarti002** [comment]
ok  will do that!

**Comment by Siddhant-K-code** [comment]
@Aarti002 this Repo. is for the Leetcode submissions only, so kindly revert the changes of CodeChef problems

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Delete The CodeChef Practice Problems

**Comment by Aarti002** [comment]
i'm sorry ! i thought this is also a practice question so it might help others

**Comment by Siddhant-K-code** [comment]
> i'm sorry ! i thought this is also a practice question so it might help others

No, its for only `LeetCode Submissions`

**Pull request closed without merging**
